"""
Migrate old allex direction cache files to the new unified format.

Old format (generated by run_expert_steering_alt.py):
  runs/{model}/expert_directions/sys_prompt_{sp}/all_experts/layer_{L}_all_experts.pt
  → stacked tensor of shape [n_experts, n_positions, d_model]

New format (used by run_expert_steering.py):
  runs/{model}/expert_directions/sys_prompt_{sp}/layer_{L}.pt
  → dict {expert_id (int): tensor[n_positions, d_model]}

The migration:
  - Unstacks the tensor along dim 0 into per-expert slices
  - Merges with any existing new-format file at the destination
    (existing entries are preserved; old-format entries overwrite on conflict)
  - Optionally deletes the source all_experts/ subdirectories when done

Usage:
  # Dry run — shows what would happen without writing anything
  python migrate_direction_cache.py --dry_run

  # Migrate all models found under runs/
  python migrate_direction_cache.py

  # Migrate a specific model only
  python migrate_direction_cache.py --model gpt-oss-20b-unsloth-bnb-4bit

  # Also delete the old all_experts/ dirs after successful migration
  python migrate_direction_cache.py --delete_old
"""

import argparse
import glob
import os
import sys

import torch


def find_old_files(runs_dir: str, model_filter: str = None):
    """
    Find all old-format all_experts cache files under runs_dir.

    Returns list of dicts with keys: old_path, new_path, model, sys_prompt, layer_idx
    """
    pattern = os.path.join(runs_dir, "**", "all_experts", "layer_*_all_experts.pt")
    old_files = glob.glob(pattern, recursive=True)

    results = []
    for old_path in sorted(old_files):
        # Parse: runs/{model}/expert_directions/sys_prompt_{sp}/all_experts/layer_{L}_all_experts.pt
        rel = os.path.relpath(old_path, runs_dir)
        parts = rel.split(os.sep)
        if len(parts) < 5:
            print(f"  [WARN] Unexpected path structure, skipping: {old_path}")
            continue

        model = parts[0]
        if model_filter and model != model_filter:
            continue

        sys_prompt_dir = parts[2]  # e.g. sys_prompt_lightweight
        filename = parts[4]        # e.g. layer_5_all_experts.pt
        try:
            layer_idx = int(filename.replace("layer_", "").replace("_all_experts.pt", ""))
        except ValueError:
            print(f"  [WARN] Could not parse layer index from filename, skipping: {filename}")
            continue

        new_path = os.path.join(
            runs_dir, model, "expert_directions", sys_prompt_dir, f"layer_{layer_idx}.pt"
        )

        results.append({
            "old_path": old_path,
            "new_path": new_path,
            "model": model,
            "sys_prompt": sys_prompt_dir,
            "layer_idx": layer_idx,
        })

    return results


def migrate_file(entry: dict, dry_run: bool = False) -> bool:
    """
    Convert one old-format file to the new dict format at the destination path.

    Returns True on success, False on error.
    """
    old_path = entry["old_path"]
    new_path = entry["new_path"]
    layer_idx = entry["layer_idx"]

    # Load old stacked tensor [n_experts, n_pos, d_model]
    try:
        stacked = torch.load(old_path, map_location="cpu")
    except Exception as e:
        print(f"  [ERROR] Could not load {old_path}: {e}")
        return False

    if not isinstance(stacked, torch.Tensor) or stacked.dim() != 3:
        print(f"  [ERROR] Unexpected content in {old_path}: "
              f"expected 3-D tensor, got {type(stacked)} "
              f"{'shape ' + str(stacked.shape) if isinstance(stacked, torch.Tensor) else ''}")
        return False

    n_experts, n_pos, d_model = stacked.shape

    # Build new dict: {expert_id (int): tensor[n_pos, d_model]}
    new_dict = {i: stacked[i] for i in range(n_experts)}

    # Merge with any existing new-format file at destination
    merged = False
    if os.path.exists(new_path):
        try:
            existing = torch.load(new_path, map_location="cpu")
            if isinstance(existing, dict):
                # Old file takes precedence for conflicts
                n_before = len(existing)
                existing.update(new_dict)
                new_dict = existing
                merged = True
                print(f"  [MERGE] layer_{layer_idx}: {n_before} existing + {n_experts} from old file "
                      f"→ {len(new_dict)} total experts")
            else:
                print(f"  [WARN] Destination {new_path} exists but is not a dict — will overwrite")
        except Exception as e:
            print(f"  [WARN] Could not load existing destination {new_path}: {e} — will overwrite")

    action = "Would write" if dry_run else "Writing"
    if not merged:
        print(f"  [OK] layer_{layer_idx}: {action} {n_experts} experts "
              f"(shape per expert: {list(stacked[0].shape)}) → {new_path}")

    if not dry_run:
        os.makedirs(os.path.dirname(new_path), exist_ok=True)
        torch.save(new_dict, new_path)

    return True


def main():
    parser = argparse.ArgumentParser(
        description="Migrate old all_experts direction cache to new per-layer dict format"
    )
    parser.add_argument(
        "--runs_dir",
        type=str,
        default="runs",
        help="Root runs directory to search (default: runs/)"
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="Migrate only this model subdirectory (default: all models)"
    )
    parser.add_argument(
        "--dry_run",
        action="store_true",
        help="Print what would be done without writing any files"
    )
    parser.add_argument(
        "--delete_old",
        action="store_true",
        help="Delete all_experts/ subdirectories after successful migration"
    )
    args = parser.parse_args()

    if not os.path.isdir(args.runs_dir):
        print(f"Error: runs directory not found: {args.runs_dir}")
        sys.exit(1)

    if args.dry_run:
        print("[DRY RUN] No files will be written or deleted.\n")

    entries = find_old_files(args.runs_dir, model_filter=args.model)
    if not entries:
        print(f"No old-format all_experts files found under {args.runs_dir}")
        sys.exit(0)

    print(f"Found {len(entries)} old-format file(s) to migrate\n")

    # Group by model/sys_prompt for cleaner output
    current_group = None
    ok_count = 0
    err_count = 0
    old_dirs_to_remove = set()

    for entry in entries:
        group = f"{entry['model']} / {entry['sys_prompt']}"
        if group != current_group:
            print(f"\n{group}")
            current_group = group

        success = migrate_file(entry, dry_run=args.dry_run)
        if success:
            ok_count += 1
            old_dirs_to_remove.add(os.path.dirname(entry["old_path"]))
        else:
            err_count += 1

    print(f"\nMigrated: {ok_count}  Errors: {err_count}")

    # Optionally delete old all_experts/ dirs
    if args.delete_old and old_dirs_to_remove:
        if err_count > 0:
            print("\n[WARN] Skipping deletion of old dirs because some files had errors.")
        else:
            import shutil
            print(f"\nDeleting {len(old_dirs_to_remove)} old all_experts/ director(ies)...")
            for d in sorted(old_dirs_to_remove):
                if args.dry_run:
                    print(f"  Would remove: {d}")
                else:
                    shutil.rmtree(d)
                    print(f"  Removed: {d}")


if __name__ == "__main__":
    main()
